site_name: Wekan
site_description: 'Wekan unofficial documentation'
site_url: 'https://wekan-doc.readthedocs.io/en/latest/'
repo_url: 'https://wekan-doc.readthedocs.io/en/latest'

nav:
    - 'Home': index.md
    - 'Installation':
        - 'Index': installation/index.md
        - 'Devuan': installation/devuan.md
        - 'Docker': installation/docker.md
        - 'Docker Compose': installation/docker-compose.md
    - 'Administration':
        - 'Index': api/index.md
        - 'Configuration':
            - 'REST Api': https://soohwa.github.io/wekan-doc/assets/html/wekan.html
            - 'WebHook': api/webhook.md
            - 'Adding Users': administration/addUsers.md
        - 'Backup / Restore':
            - 'Devuan': backup/devuan.md
            - 'Docker': backup/docker.md
    - 'Features':
        - 'Index': feature/index.md
        - 'Custom Fields': feature/customFields.md
        - 'IFTTT': feature/ifttt.md
    - 'Developpement':
        - 'Index': build/index.md
        - 'Building':
            - 'Package': build/package.md
            - 'Bundle': build/bundle.md
        - 'Translations': build/translations.md

# Configuration
theme:
  name: 'readthedocs'
  language: 'en'
  palette:
    primary: 'blue'
    accent: 'blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo: 'duplicatilogo.png'
  favicon: 'favicon.ico'
  feature:
    tabs: false

extra:
  manifest: 'manifest.webmanifest'
  social:
    - type: 'github'
      link: 'https://github.com/wekan/wekan'
    - type: 'translation'
      link: 'https://www.transifex.com/wekan/wekan/dashboard'
    - type: 'github'
      link: 'https://github.com/wekan/wekan'

